// winmux-server Kotlin SDK. Types under dev.winmux.sdk (Frames.kt, Models.kt)
// are generated by sdk-gen (`npm run gen`); the client + WS wrapper are
// hand-written. Version tracks the server (kept in sync by sdk-gen).
plugins {
    kotlin("jvm") version "2.0.21"
    kotlin("plugin.serialization") version "2.0.21"
}

group = "dev.winmux"
version = "2.0.0"

repositories { mavenCentral() }

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    testImplementation(kotlin("test"))
}

tasks.test { useJUnitPlatform() }
kotlin { jvmToolchain(17) }
