// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonAction } from "./AddonAction";

/**
 * Static declaration of one add-on. Built-in add-ons ship their
 * manifest compiled in ([`builtin_registry`]); the schema also
 * serialises so a future community-add-ons directory can drop JSON.
 */
export type AddonManifest = { 
/**
 * Stable key: "winmux-cli" | "tmux-conf" | "hooks" | "insights".
 */
id: string, name: string, description: string, 
/**
 * Version this desktop build ships / can install.
 */
version: string, 
/**
 * Other add-on ids that must be installed first.
 */
dependencies: Array<string>, install: AddonAction, uninstall: AddonAction, update: AddonAction, 
/**
 * Prints the installed version (empty / non-zero ⇒ absent).
 */
detect: AddonAction, 
/**
 * Needs sudo to install (drives the UI warning + wizard gating).
 */
needs_sudo: boolean, };