// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime status of an add-on on a given workspace (vs the static
 * manifest). Returned by `addon_list` to the Settings table / wizard.
 */
export type AddonStatus = { id: string, installed: boolean, installed_version: string | null, available_version: string, update_available: boolean, 
/**
 * An install/update/remove is in flight for this (workspace, id).
 */
busy: boolean, last_error: string | null, };