// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserState = { url: string, home_url: string | null, history: Array<string>, forward_localhost: boolean, last_loaded_url: string | null, };