// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 78: Claude subscription-usage display options. The usage data
 * itself comes from `claude -p "/usage"` over SSH (see claude_usage.rs);
 * these settings only control how the global % indicator is shown and how
 * often a live connection auto-refreshes it.
 */
export type ClaudeUsageSettings = { 
/**
 * Show the compact usage % indicator at the top of the sidebar.
 */
show_top_indicator: boolean, 
/**
 * `"percent"` (colored NN% text) or `"bar"`. A String (not an enum) to
 * match the sidebar_mode / rtl_mode pattern → plain TS union.
 */
display_mode: string, 
/**
 * Auto-refresh cadence for the active *live* (non-headless) workspace,
 * in minutes. `0` = off (manual refresh only). The calls are free, so a
 * modest interval keeps the indicator fresh without user action.
 */
auto_refresh_minutes: number, };