// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsage } from "./ModelUsage";

/**
 * Parsed `/usage` snapshot for one workspace's Claude account.
 */
export type ClaudeUsage = { session_pct: number, session_reset: string, week_pct: number, week_reset: string, 
/**
 * Per-model weekly rows (excludes the "all models" aggregate).
 */
models: Array<ModelUsage>, 
/**
 * Raw "Last 24h" contributing lines (header + indented bullets).
 */
contributing_24h: Array<string>, 
/**
 * Raw "Last 7d" contributing lines.
 */
contributing_7d: Array<string>, fetched_unix: bigint, };