// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 65.B: result of a successful connect-existing run.
 */
export type ConnectExistingResult = { workspace_id: string, workspace_name: string, key_path: string, };