// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Connection = { "type": "local", shell: string | null, } | { "type": "ssh", host: string, user: string, port: number, key_path: string | null, };