// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 65.B: inputs for the "Connect to existing server" execute step.
 */
export type ConnectExistingInput = { host: string, port: number, 
/**
 * The account we connect AS with the password to do the setup work.
 */
auth_user: string, 
/**
 * One-shot password — used only for the setup connection, zeroized
 * after, never written to disk (Rule #2).
 */
password: string, 
/**
 * The account we set up key-only access FOR (existing or new).
 */
target_user: string, 
/**
 * true → create `target_user` (requires can_sudo); false → install
 * the key for an existing account.
 */
create_new_user: boolean, 
/**
 * New-user only: add to the admin group for sudo.
 */
grant_sudo: boolean, 
/**
 * Admin group from discovery ("sudo" / "wheel").
 */
sudo_group: string, 
/**
 * New workspace name (Branch 2), or None.
 */
workspace_name: string | null, 
/**
 * When set, add this machine to an existing workspace instead of
 * creating one (Branch 1).
 */
existing_workspace_id: string | null, };