// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedItemState } from "./FeedItemState";

export type FeedItem = { request_id: string, kind: string, subkind: string, pane_id: string | null, workspace_id: string | null, title: string, summary: string, payload: unknown, state: FeedItemState, created_ms: number, blocking: boolean, };