// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatingWindowMode } from "./FloatingWindowMode";
import type { Rect } from "./Rect";

/**
 * Phase 63: persisted state for ONE floating-window kind, shared across
 * workspaces (the window is per-workspace, but its mode + geometry
 * preferences are global per kind — matches Yossi's spec).
 */
export type FloatingWindowState = { mode: FloatingWindowMode, 
/**
 * Last Float-mode rect (in-app, over the workspace).
 */
float_rect: Rect | null, 
/**
 * Last Pop-out OS-window rect (screen coordinates).
 */
popout_rect: Rect | null, 
/**
 * Monitor index the Pop-out last lived on; if that monitor is gone
 * next launch, fall back to the main window's display.
 */
popout_display: number | null, 
/**
 * Last Pane-mode width (px).
 */
pane_width: number | null, };