// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatingWindowState } from "./FloatingWindowState";

/**
 * Phase 63: both floating-window kinds.
 */
export type FloatingWindows = { browser: FloatingWindowState, filemanager: FloatingWindowState, };