// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Font = { ui_family: string, ui_size_pt: number, terminal_family: string, terminal_size_pt: number, 
/**
 * Stretch goal: optional URL to a CSS stylesheet (e.g. Google Fonts)
 * that the frontend injects via <link rel="stylesheet"> so the user
 * can pick a non-installed family and have it fetched at runtime.
 * Empty / None = no extra fonts loaded.
 */
web_font_url: string | null, };