// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hooks = { enabled: boolean, agents: Array<string>, policy_preset: string, 
/**
 * Phase 18.1: which PreToolUse matcher to install in the agent's
 * settings.json. `"restrictive"` (default) only matches risky tools
 * (`Bash|Write|Edit|MultiEdit|NotebookEdit|Task`); `"all"` matches
 * every tool (`.*`) so EVERY action surfaces a winmux card; `"custom"`
 * keeps whatever the user hand-edited locally and is never overwritten
 * by `winmux setup-hooks`. The setting is consumed by the desktop's
 * remote-side setup-hooks call (Phase 18 wraps `agent.setup_hooks`).
 */
matcher_mode: string, 
/**
 * Phase 66 (66.D): master switch for the 3-state policy engine
 * (auto / gate / block) that runs in the desktop `feed.push` handler.
 * When false, every pre-tool-use request becomes a blocking card (the
 * pre-66 behavior). Default true. Older settings.json without the
 * field loads with the engine ON.
 */
policy_enabled: boolean, 
/**
 * Phase 66 (66.B): when true (default), the SSH bootstrap auto-runs
 * `winmux setup-hooks` on the remote after deploying the CLI, so a
 * fresh server starts surfacing permission cards without the user
 * invoking setup-hooks by hand. No-op if Claude Code isn't installed
 * remotely. Older settings.json loads with auto-install ON.
 */
auto_install: boolean, 
/**
 * Phase 66.F: user-defined BLOCK patterns, one per entry, merged into
 * the built-in list by the desktop policy engine (rpc_server
 * feed.push). Same matching semantics as the built-ins: lowercased,
 * whitespace-collapsed substring match against the whole command and
 * each chained segment. Desktop-side enforcement only — the CLI's
 * static fallback keeps the built-ins. `#[serde(default)]` so older
 * settings.json loads with empty lists.
 */
custom_block: Array<string>, 
/**
 * Phase 66.F: user-defined GATE patterns (see `custom_block`). Block
 * beats gate when a command matches both.
 */
custom_gate: Array<string>, };