// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookType = "pre-tool-use" | "notification" | "stop" | "session-end" | "post-tool-use" | "subagent-stop" | "user-prompt-submit" | "pre-compact" | "session-start";