// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookType } from "./HookType";

/**
 * beta.3: per-hook toggles: which types the backend actually processes and
 * which of those play a sound on the toast.
 *
 * Migration policy (see `default_hook_notifications` / `migrate_settings`):
 * when an older settings.json has no `hook_notifications` object, the
 * defaults kick in — the interactive-4 (PreToolUse / Notification / Stop /
 * SessionEnd) are enabled; the interactive-3 (PreToolUse / Notification /
 * Stop) additionally get sound; sound_master starts on. The verbose
 * observability hooks (PostToolUse / SubagentStop / UserPromptSubmit /
 * PreCompact / SessionStart) are off across the board.
 */
export type HookSettings = { enabled_types: Array<HookType>, sound_types: Array<HookType>, sound_master: boolean, };