// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 18: per-user state for the hooks-outdated banner. Tracked
 * separately from `Hooks` (which is per-agent enablement) because
 * the dismiss list belongs to the UI layer, not to the hook spec.
 */
export type HooksUpdates = { show_banners: boolean, 
/**
 * `agent → [version-strings-the-user-said-skip]`. Empty entries
 * are tolerated so a Clear-from-Settings can keep the agent key
 * around without re-listing every dismissed version.
 */
dismissed: { [key: string]: Array<string> }, };