// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Hooks = { enabled: boolean, agents: Array<string>, policy_preset: string, 
/**
 * Phase 18.1: which PreToolUse matcher to install in the agent's
 * settings.json. `"restrictive"` (default) only matches risky tools
 * (`Bash|Write|Edit|MultiEdit|NotebookEdit|Task`); `"all"` matches
 * every tool (`.*`) so EVERY action surfaces a winmux card; `"custom"`
 * keeps whatever the user hand-edited locally and is never overwritten
 * by `winmux setup-hooks`. The setting is consumed by the desktop's
 * remote-side setup-hooks call (Phase 18 wraps `agent.setup_hooks`).
 */
matcher_mode: string, };