// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 75: debug.log retention. The log auto-rotates at a size cap and is
 * pruned on startup once older than `retention_days`.
 */
export type LogsSettings = { 
/**
 * Delete debug logs untouched for this many days (0 = keep forever).
 */
retention_days: number, };