// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model's weekly usage row (e.g. `Current week (Fable): 16% used …`).
 */
export type ModelUsage = { name: string, pct: number, reset: string, };