// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notifications = { 
/**
 * Master switch — when false, no hook toasts at all.
 */
toast_enabled: boolean, sound_enabled: boolean, 
/**
 * Claude session started — noisy, default OFF.
 */
toast_session_start: boolean, 
/**
 * Claude session ended — default OFF.
 */
toast_session_end: boolean, 
/**
 * Claude finished a task (Stop) — useful, default ON.
 */
toast_stop: boolean, 
/**
 * Claude needs you (Notification event) — critical, default ON.
 */
toast_notification: boolean, 
/**
 * A tool needs approval (PreToolUse gate) — must respond, default ON.
 */
toast_gate: boolean, 
/**
 * A dangerous tool was blocked — security insight, default ON.
 */
toast_block: boolean, };