// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 63: a window rectangle in logical pixels.
 */
export type Rect = { x: number, y: number, width: number, height: number, };