// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 65: what a one-shot password probe learned about a server, used
 * to drive the "Connect to existing server" wizard's choice step.
 */
export type ServerDiscovery = { 
/**
 * The login user is uid 0.
 */
is_root: boolean, 
/**
 * Login user is root OR has passwordless sudo (i.e. can create a
 * new user + grant sudo). Drives whether "create new user" is
 * offered.
 */
can_sudo: boolean, 
/**
 * Admin group to add a new user to for sudo — "sudo" on
 * Debian/Ubuntu, "wheel" on RHEL/Fedora. Defaults to "sudo".
 */
sudo_group: string, 
/**
 * Real interactive accounts (uid 0 or 1000..65000, with a login
 * shell — not nologin/false/sync), sorted + deduped.
 */
users: Array<string>, };