// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeOptions } from "./ClaudeOptions";
import type { Font } from "./Font";
import type { Hooks } from "./Hooks";
import type { HooksUpdates } from "./HooksUpdates";
import type { I18n } from "./I18n";
import type { MigrationFlags } from "./MigrationFlags";
import type { Notifications } from "./Notifications";
import type { Shortcuts } from "./Shortcuts";
import type { TerminalSettings } from "./TerminalSettings";
import type { Theme } from "./Theme";
import type { Updates } from "./Updates";

export type Settings = { version: number, theme: Theme, font: Font, terminal: TerminalSettings, hooks: Hooks, notifications: Notifications, updates: Updates, i18n: I18n, 
/**
 * Phase 16. `#[serde(default)]` so pre-16 settings.json files
 * load with the built-in defaults.
 */
shortcuts: Shortcuts, 
/**
 * Phase 17. Claude session summary options.
 */
claude: ClaudeOptions, 
/**
 * Phase 18. Hooks-outdated banner show/skip state.
 */
hooks_updates: HooksUpdates, 
/**
 * Phase 32.B. When true, suppress the "set up SSH key
 * authentication?" offer after a password-auth connect. Persisted
 * when the user ticks "Don't show again" in the offer modal.
 * `#[serde(default)]` so older settings.json loads cleanly.
 */
ssh_key_offer_disabled: boolean, 
/**
 * Phase 41. When true (default), activating an SSH workspace
 * establishes a background SSH session so the tmux session picker and
 * the remote file manager populate without the user opening a
 * terminal pane first. Disable to defer the connection until a pane
 * connects. `default = "default_true"` keeps pre-41 settings.json
 * backwards-compatible (missing field → true).
 */
auto_connect_on_workspace_select: boolean, 
/**
 * Phase 39.B. One-time data migrations that have already run.
 */
migrations: MigrationFlags, };