// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeOptions } from "./ClaudeOptions";
import type { FloatingWindows } from "./FloatingWindows";
import type { Font } from "./Font";
import type { Hooks } from "./Hooks";
import type { HooksUpdates } from "./HooksUpdates";
import type { I18n } from "./I18n";
import type { LogsSettings } from "./LogsSettings";
import type { MigrationFlags } from "./MigrationFlags";
import type { Notifications } from "./Notifications";
import type { Shortcuts } from "./Shortcuts";
import type { SttSettings } from "./SttSettings";
import type { TerminalSettings } from "./TerminalSettings";
import type { Theme } from "./Theme";
import type { Updates } from "./Updates";

export type Settings = { version: number, theme: Theme, font: Font, terminal: TerminalSettings, hooks: Hooks, notifications: Notifications, updates: Updates, i18n: I18n, 
/**
 * Phase 16. `#[serde(default)]` so pre-16 settings.json files
 * load with the built-in defaults.
 */
shortcuts: Shortcuts, 
/**
 * Phase 17. Claude session summary options.
 */
claude: ClaudeOptions, 
/**
 * Phase 18. Hooks-outdated banner show/skip state.
 */
hooks_updates: HooksUpdates, 
/**
 * Phase 32.B. When true, suppress the "set up SSH key
 * authentication?" offer after a password-auth connect. Persisted
 * when the user ticks "Don't show again" in the offer modal.
 * `#[serde(default)]` so older settings.json loads cleanly.
 */
ssh_key_offer_disabled: boolean, 
/**
 * Phase 41. When true (default), activating an SSH workspace
 * establishes a background SSH session so the tmux session picker and
 * the remote file manager populate without the user opening a
 * terminal pane first. Disable to defer the connection until a pane
 * connects. `default = "default_true"` keeps pre-41 settings.json
 * backwards-compatible (missing field → true).
 */
auto_connect_on_workspace_select: boolean, 
/**
 * Phase 49-C: optional auto-delete of empty + stale workspaces at
 * startup. `None` (default) = disabled. Range 1-90 days enforced
 * by the UI; the backend sweep treats any non-zero positive value
 * as a valid TTL. A workspace is "empty" for sweep purposes when
 * it has no live SSH sessions and its `last_active_at` is older
 * than the TTL.
 */
auto_destroy_empty_workspaces_days: number | null, 
/**
 * Phase 39.B. One-time data migrations that have already run.
 */
migrations: MigrationFlags, 
/**
 * Phase 58. Voice input (speech-to-text). Default backend is the
 * browser-native Web Speech API; users with privacy / offline
 * needs can point at a local Whisper-compatible endpoint.
 * `#[serde(default)]` so older settings.json files load with
 * `enabled = false` + the default backend.
 */
stt: SttSettings, 
/**
 * Phase 62.B (item I): sidebar display mode — "full" | "icons" |
 * "hidden". A String (not an enum) to match the rtl_mode /
 * matcher_mode pattern and keep the TS binding a plain union.
 * Persisted here (atomic settings write, Rule #7) so the choice
 * survives restarts. `default = "full"` keeps older settings.json
 * loading unchanged. Phase 65.P: only "full" / "icons" are written
 * now; a legacy "hidden" value is migrated to "icons" on the
 * frontend at read time (App.tsx sidebarMode()).
 */
sidebar_mode: string, 
/**
 * Phase 63: per-kind (browser / filemanager) floating-window state —
 * which of the 3 modes each is in, plus the remembered geometry for
 * Float / Pop-out / Pane. `#[serde(default)]` so older settings.json
 * loads with both kinds defaulting to Float (current behavior).
 */
floating_windows: FloatingWindows, 
/**
 * Phase 75: debug-log hygiene (retention). `#[serde(default)]` so older
 * settings.json files load with the built-in defaults.
 */
logs: LogsSettings, };