// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 16: configurable keyboard shortcuts. Stored as human-readable
 * `Ctrl+Shift+X` strings — parsed in the frontend (see
 * `src/shortcuts.ts`) so users can hand-edit settings.json and the
 * next launch picks up the change.
 */
export type Shortcuts = { copy: string, paste: string, select_all: string, find: string, new_workspace: string, toggle_notes: string, toggle_settings: string, 
/**
 * Phase 17: trigger a manual Claude session summary. Default
 * Ctrl+Alt+B (B for "brief"). #[serde(default)] so pre-17
 * settings.json files don't need to be touched.
 */
summarize_claude: string, 
/**
 * When true and the terminal has a selection, plain Ctrl+C copies
 * to clipboard instead of sending SIGINT. Matches Windows Terminal
 * + most modern terminal apps. Set to false to always send SIGINT.
 */
copy_on_select_with_ctrl_c: boolean, };