// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SttBackend } from "./SttBackend";

/**
 * Phase 58: speech-to-text settings.
 *
 * - `Webspeech` uses `window.SpeechRecognition` directly in the
 *   frontend (Chromium / WebView2 ships with it; Firefox does not —
 *   not a concern for Tauri's WebView2-only Windows build, but worth
 *   flagging if we ever target Linux's WebKitGTK).
 * - `Local` POSTs the recorded audio bytes to a user-configurable
 *   HTTP endpoint (whisper.cpp's server, faster-whisper-server,
 *   OpenAI-compatible local proxies). Field shape mirrors OpenAI's
 *   /v1/audio/transcriptions: multipart with `file` (audio bytes) +
 *   `language`.
 */
export type SttSettings = { 
/**
 * Master on/off. Default off — opt-in feature, no mic access
 * requested until the user flips this.
 */
enabled: boolean, 
/**
 * Which backend to use when recording. Defaults to Webspeech.
 */
backend: SttBackend, 
/**
 * Required when `backend = Local`. Skipped when None.
 */
local_endpoint: string | null, 
/**
 * BCP-47 tag or "auto". Defaults to "auto" — the Web Speech API
 * accepts it and most Whisper servers default to language
 * detection when the param is missing or "auto".
 */
language: string, 
/**
 * Push-to-talk keybinding. Parsed by the existing shortcut-table
 * helpers (Ctrl/Shift/Alt + key). Default Ctrl+Shift+M (M for
 * microphone).
 */
push_to_talk_hotkey: string, };