// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = { cursor_style: string, scrollback_lines: number, bidi_enabled: boolean, allow_proposed_api: boolean, 
/**
 * Phase 15.A: how to handle Hebrew / Arabic in the terminal.
 * One of "auto_per_line" (default, Termius-style — DOM renderer
 * + dir="auto" on every row), "bidi_reorder" (legacy v1, WebGL +
 * bidi-js logical→visual reorder), or "off" (WebGL, no reorder).
 * New panes pick up the renderer immediately; live mode swaps
 * affect the reorder pipeline on currently-open panes.
 */
rtl_mode: string, 
/**
 * Phase tmux-conf: when true (default), tmux is launched with
 * `-f ~/.winmux/tmux.conf` so the bundled scrollback-friendly
 * config applies (wheel scrolls the scrollback ring instead of
 * shell history, 50k-line buffer, mouse on, sane truecolour).
 * Set false to fall back to the user's own `~/.tmux.conf`. The
 * conf file is uploaded by the bootstrap regardless, so the
 * toggle takes effect on the NEXT pane connect.
 */
use_winmux_tmux_config: boolean, };