// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = { cursor_style: string, scrollback_lines: number, bidi_enabled: boolean, allow_proposed_api: boolean, 
/**
 * Phase 15.A: how to handle Hebrew / Arabic in the terminal.
 * One of "auto_per_line" (default, Termius-style — DOM renderer
 * + dir="auto" on every row), "bidi_reorder" (legacy v1, WebGL +
 * bidi-js logical→visual reorder), or "off" (WebGL, no reorder).
 * New panes pick up the renderer immediately; live mode swaps
 * affect the reorder pipeline on currently-open panes.
 */
rtl_mode: string, 
/**
 * Phase tmux-conf: when true (default), tmux is launched with
 * `-f ~/.winmux/tmux.conf` so the bundled scrollback-friendly
 * config applies (wheel scrolls the scrollback ring instead of
 * shell history, 50k-line buffer, mouse on, sane truecolour).
 * Set false to fall back to the user's own `~/.tmux.conf`. The
 * conf file is uploaded by the bootstrap regardless, so the
 * toggle takes effect on the NEXT pane connect.
 */
use_winmux_tmux_config: boolean, 
/**
 * Phase HH: mirror the physical Left/Right arrow keys when the
 * terminal line under the cursor is right-to-left (Hebrew/Arabic).
 * In an RTL line the visual "right" is logical "left", so without
 * this the arrows feel inverted. Only takes effect on RTL lines —
 * LTR lines are unaffected — so it's safe to leave on (default true).
 */
mirror_arrows_rtl: boolean, 
/**
 * v0.4.4 (RTL Approach C): auto-flip each terminal line's paragraph
 * direction from its text — a line with any Hebrew/Arabic char renders
 * RTL (mixed or pure), a pure-Latin line renders LTR. Only affects the
 * `auto_per_line` rtl_mode. Default true; set false for classic
 * LTR-only terminal behaviour.
 */
auto_direction: boolean, 
/**
 * v0.4.4-beta.2: on connect/attach, clear stale mouse-tracking modes an
 * unclean app exit (vim/fzf/less/htop killed) can leave on — which makes
 * the bare shell print `\e[<..M` mouse escapes as text. Default true; a
 * manual "Reset terminal" (Ctrl+Alt+R) is always available regardless.
 */
auto_reset_on_connect: boolean, };