// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnsiPalette } from "./AnsiPalette";

export type Theme = { preset: string, accent: string, background: string, surface: string, border: string, text_primary: string, text_secondary: string, success: string, warning: string, error: string, ansi: AnsiPalette, };