// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Updates = { check_on_startup: boolean, auto_download: boolean, manifest_url: string | null, last_check_iso: string | null, last_seen_version: string | null, 
/**
 * Phase 65 (U): versions the user chose to skip — the
 * `update:available` banner stays suppressed for these until a
 * newer version appears. Older settings.json without this field
 * load with an empty list.
 */
skipped_versions: Array<string>, 
/**
 * Phase 65 (U): "remind me later" — suppress the banner until this
 * ISO timestamp passes. None = no active snooze.
 */
remind_after_iso: string | null, };