// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Updates = { check_on_startup: boolean, auto_download: boolean, manifest_url: string | null, last_check_iso: string | null, last_seen_version: string | null, };