// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceGroup = { id: string, name: string, 
/**
 * One of the eight cmux-A palette colors (frontend-picked hex).
 * Not validated on the backend — the picker constrains it.
 */
color: string, 
/**
 * Persisted collapsed/open state. `#[serde(default)]` so an older
 * workspaces.json (before A2) that grows a group entry via a
 * hand-edit still loads.
 */
is_collapsed: boolean, };
