// GENERATED by sdk-gen (winmux 2.0.0) — DO NOT EDIT. Regenerate: npm run gen.
// REST DTOs (generated from the server OpenAPI component schemas).
package dev.winmux.sdk

import kotlinx.serialization.*
import kotlinx.serialization.json.*

@Serializable
data class ClientInfo(
    @SerialName("client_id") val clientId: String,
    @SerialName("device_name") val deviceName: String,
    val files: List<String>,
    @SerialName("latest_entry") val latestEntry: Long,
    @SerialName("log_dir") val logDir: String
)

@Serializable
data class ClientsBody(
    val clients: List<ClientInfo>
)

@Serializable
data class ErrEvent(
    val error: String
)

@Serializable
data class ErrorDetail(
    val location: String? = null,
    val message: String? = null,
    val value: JsonElement? = null
)

@Serializable
data class ErrorModel(
    val detail: String? = null,
    val errors: List<ErrorDetail>? = null,
    val instance: String? = null,
    val status: Long? = null,
    val title: String? = null,
    val type: String? = null
)

@Serializable
data class FileEntry(
    val modified: Long,
    val name: String,
    val size: Long,
    val type: String
)

@Serializable
data class FileListBody(
    val cwd: String,
    val entries: List<FileEntry>
)

@Serializable
data class FormFile(
    val ContentType: String,
    val Filename: String,
    val IsSet: Boolean,
    val Size: Long
)

@Serializable
data class HealthBody(
    val ok: Boolean,
    val version: String
)

@Serializable
data class LineEvent(
    val line: String
)

@Serializable
data class OkBody(
    val ok: Boolean
)

@Serializable
data class ReadBody(
    val lines: List<String>,
    val truncated: Boolean
)

@Serializable
data class UploadResultBody(
    val path: String,
    val sha256: String,
    val size: Long
)

@Serializable
data class VersionBody(
    @SerialName("api_versions") val apiVersions: List<Long>,
    @SerialName("frame_version") val frameVersion: Long,
    val name: String,
    val version: String
)

