//! Phase 51.D: thin shim around `winmux-bootstrap`.
//!
//! The actual CLI deploy logic moved to its own crate; this module
//! does only the Tauri-specific resource resolution (manifest +
//! bundled Linux binary lookup via `app.path().resolve(...)`) and
//! delegates the russh + SFTP work to `winmux_bootstrap::bootstrap`.

use tauri::AppHandle;

use crate::dlog;
use crate::SshClient;

// Re-export the public surface so existing crate::remote_bootstrap::*
// callsites continue to resolve unchanged.
pub use winmux_bootstrap::{BootstrapStatus, PATH_RC_SNIPPET};

// Phase 62.B: embed the bootstrap payloads in the binary instead of
// resolving them via `BaseDirectory::Resource`. The resource lookup
// works for an INSTALLED bundle (resources/ sits next to the exe) but
// NOT for the standalone debug exe Yossi runs by copying just app.exe
// into winmux-debug-test\ — there `resources/remote-manifest.json`
// doesn't exist and the read failed with "os error 3" (silent WARN,
// then bootstrap couldn't upload the CLI). These three files are
// committed AND regenerated by build-linux-cli.ps1 (the beforeBuild
// step), so include_*! always resolves at compile time and the exe is
// self-contained regardless of where it's copied.
const REMOTE_MANIFEST: &str = include_str!("../resources/remote-manifest.json");
const WINMUX_LINUX_X64: &[u8] = include_bytes!("../resources/winmux-linux-x64");
const WINMUX_TMUX_CONF: &[u8] = include_bytes!("../resources/winmux-tmux.conf");

/// Phase 62.B: resolve a bootstrap payload by the `path` value used in
/// the manifest. Embedded — never touches the filesystem. An unknown
/// name means the manifest and this match arm drifted apart (caught in
/// dev, not silently at a user's connect).
fn read_resource_bytes(rel: &str) -> Result<Vec<u8>, String> {
    let bytes: &[u8] = match rel {
        "winmux-linux-x64" => WINMUX_LINUX_X64,
        "winmux-tmux.conf" => WINMUX_TMUX_CONF,
        other => {
            return Err(format!(
                "unknown bootstrap resource {other:?} — manifest/code drift"
            ))
        }
    };
    dlog(&format!("bootstrap: embedded resource {rel:?} → {} bytes", bytes.len()));
    Ok(bytes.to_vec())
}

/// Phase 6.2 → Phase 51.D → 62.B: hand the embedded manifest + payload
/// loader to `winmux_bootstrap::bootstrap` for the russh + SFTP work.
/// `_app` is kept in the signature for call-site stability; resource
/// resolution no longer needs it.
pub async fn bootstrap(
    handle: &mut russh::client::Handle<SshClient>,
    _app: &AppHandle,
    force: bool,
) -> Result<BootstrapStatus, String> {
    dlog(&format!(
        "bootstrap: using embedded manifest ({} bytes)",
        REMOTE_MANIFEST.len()
    ));
    let manifest = winmux_bootstrap::parse_manifest(REMOTE_MANIFEST)?;
    let loader = |rel: &str| read_resource_bytes(rel);
    winmux_bootstrap::bootstrap(handle, manifest, &loader, force).await
}
