// emit-specs.mjs — collect the three source-of-truth specs into sdk-gen/specs/:
//   openapi.json      — GENERATED by the server (`winmux-server openapi`)
//   asyncapi.json     — hand-authored WS contract (internal/api)
//   frames.schema.json — canonical WS frame JSON-Schema (internal/api)
// The generators + the CI drift-guard read from specs/, so the SDKs never
// depend on a running server.
import { execFileSync } from "node:child_process";
import { mkdirSync, copyFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const serverDir = resolve(repo, "app/src-tauri/server");
const apiDir = resolve(serverDir, "internal/api");
const specs = resolve(here, "specs");
mkdirSync(specs, { recursive: true });

// OpenAPI: ask the server binary to emit it (nil providers, no data dir).
const openapi = execFileSync("go", ["run", "./cmd/winmux-server", "openapi"], {
  cwd: serverDir,
  encoding: "utf8",
  maxBuffer: 32 * 1024 * 1024,
});
// Normalize to pretty JSON so the committed spec + drift diff are stable.
writeFileSync(resolve(specs, "openapi.json"), JSON.stringify(JSON.parse(openapi), null, 2) + "\n");

for (const f of ["asyncapi.json", "frames.schema.json"]) {
  copyFileSync(resolve(apiDir, f), resolve(specs, f));
}
console.log("specs → sdk-gen/specs/ (openapi.json, asyncapi.json, frames.schema.json)");
