// gen-kotlin.mjs — generate the Kotlin SDK's typed layer from the specs with a
// small, deterministic emitter (kotlinx.serialization). We hand-roll the emitter
// rather than use quicktype/openapi-generator because: (a) quicktype's JSON
// Schema $ref resolution + discriminated-union support are unreliable here, and
// (b) openapi-generator needs a JVM. The output is idiomatic kotlinx (a sealed
// WinmuxFrame with @SerialName subclasses + @Serializable DTOs) and is
// drift-guarded by regeneration, same as the TS side.
//
//   sdk/kotlin/src/main/kotlin/dev/winmux/sdk/Frames.kt — WS frame union
//   sdk/kotlin/src/main/kotlin/dev/winmux/sdk/Models.kt  — REST DTOs
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specs = resolve(here, "specs");
const pkg = "dev.winmux.sdk";
const outDir = resolve(here, "..", "sdk", "kotlin", "src", "main", "kotlin", "dev", "winmux", "sdk");
mkdirSync(outDir, { recursive: true });

const openapi = JSON.parse(readFileSync(resolve(specs, "openapi.json"), "utf8"));
const frames = JSON.parse(readFileSync(resolve(specs, "frames.schema.json"), "utf8"));
const version = openapi.info.version;

// ── type mapping ──────────────────────────────────────────────────────────
// Resolve a JSON-Schema property node to a Kotlin type. Refs map to the target
// class name; untyped/empty schemas fall back to kotlinx JsonElement.
function ktType(node) {
  if (!node || typeof node !== "object") return "JsonElement";
  if (typeof node.$ref === "string") return node.$ref.split("/").pop();
  if (node.const !== undefined) return "String";
  // OpenAPI 3.1 encodes nullable as a type union e.g. ["array","null"]; take
  // the concrete member (field-level nullability comes from `required`).
  const t = Array.isArray(node.type) ? node.type.find((x) => x !== "null") : node.type;
  switch (t) {
    case "string":
      return "String";
    case "integer":
      return "Long";
    case "number":
      return "Double";
    case "boolean":
      return "Boolean";
    case "array":
      return `List<${ktType(node.items ?? {})}>`;
    case "object":
      return "JsonElement";
    default:
      return "JsonElement";
  }
}

// Merge allOf envelope refs into a flat {props, required} view for a frame.
function flatten(schema, table) {
  let props = { ...(schema.properties ?? {}) };
  let required = new Set(schema.required ?? []);
  for (const part of schema.allOf ?? []) {
    const ref = part.$ref ? table[part.$ref.split("/").pop()] : part;
    if (!ref) continue;
    props = { ...(ref.properties ?? {}), ...props };
    for (const r of ref.required ?? []) required.add(r);
  }
  return { props, required };
}

const header = (title) =>
  `// GENERATED by sdk-gen (winmux ${version}) — DO NOT EDIT. Regenerate: npm run gen.\n` +
  `// ${title}\npackage ${pkg}\n\nimport kotlinx.serialization.*\nimport kotlinx.serialization.json.*\n\n`;

function fieldLines(props, required, { omitType }) {
  const lines = [];
  for (const [name, node] of Object.entries(props)) {
    if (omitType && name === "type") continue; // discriminator handled by @SerialName
    const kt = ktType(node);
    const req = required.has(name);
    const camel = name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
    const ann = camel !== name ? `@SerialName("${name}") ` : "";
    const type = req ? kt : `${kt}? = null`;
    lines.push(`    ${ann}val ${camel}: ${type}`);
  }
  return lines.join(",\n");
}

// ── Frames.kt — sealed WinmuxFrame with @SerialName subclasses ─────────────
const frameDefs = frames.$defs ?? {};
let fk = header("WebSocket frame contract (PHASE-77-DESIGN §4.4). Discriminator: `type`.");
fk += `/** Shared Json with the frame discriminator + lenient unknown-key handling. */\n`;
fk += `object WinmuxJson {\n    val instance: Json = Json {\n        classDiscriminator = "type"\n        ignoreUnknownKeys = true\n        encodeDefaults = false\n    }\n}\n\n`;
fk += `@Serializable\nsealed interface WinmuxFrame\n\n`;
for (const [name, schema] of Object.entries(frameDefs)) {
  if (name === "SessionEventEnvelope") continue;
  const typeConst = schema.properties?.type?.const;
  if (!typeConst) continue;
  const { props, required } = flatten(schema, frameDefs);
  const body = fieldLines(props, required, { omitType: true });
  // A frame with only the discriminator (e.g. unsubscribe) can't be a data
  // class (needs ≥1 param) — emit a serializable data object instead.
  if (!body) {
    fk += `@Serializable\n@SerialName("${typeConst}")\ndata object ${name} : WinmuxFrame\n\n`;
  } else {
    fk += `@Serializable\n@SerialName("${typeConst}")\ndata class ${name}(\n${body}\n) : WinmuxFrame\n\n`;
  }
}
writeFileSync(resolve(outDir, "Frames.kt"), fk);

// ── Models.kt — @Serializable REST DTOs ────────────────────────────────────
const schemas = openapi.components?.schemas ?? {};
let mk = header("REST DTOs (generated from the server OpenAPI component schemas).");
for (const [name, schema] of Object.entries(schemas)) {
  if ((schema.type ?? "object") !== "object" || !schema.properties) continue;
  const body = fieldLines(schema.properties, new Set(schema.required ?? []), { omitType: false });
  mk += `@Serializable\ndata class ${name}(\n${body}\n)\n\n`;
}
writeFileSync(resolve(outDir, "Models.kt"), mk);

console.log(`Kotlin SDK types generated (v${version})`);
