/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * winmux-server WebSocket frame contract (PHASE-77-DESIGN §4.4, frame_version 2). Every frame is a flat JSON object discriminated by `type`. Envelope fields (seq, session_id, ts) sit alongside the type-specific fields. snake_case throughout, matching the REST surface. SDK generators turn this into a Kotlin sealed interface / TS tagged union.
 */
export type WinmuxFrame =
  | HelloFrame
  | UserInputFrame
  | HookDecisionFrame
  | InterruptFrame
  | UnsubscribeFrame
  | HookRequestFrame
  | HookResolvedFrame
  | AssistantTextFrame
  | ToolUseFrame
  | ToolResultFrame
  | StatusFrame
  | ErrorFrame
  | NotificationFrame;
/**
 * Server→client: a blocking permission ask. Pending until the first hook_decision (or timeout).
 */
export type HookRequestFrame = SessionEventEnvelope & {
  type?: "hook_request";
  req_id: string;
  tool_name?: string;
  tool_input?: unknown;
  decision_required?: boolean;
};
/**
 * Server→client: a hook was answered (or timed out); broadcast to all subscribers so late clients converge.
 */
export type HookResolvedFrame = SessionEventEnvelope & {
  type?: "hook_resolved";
  req_id: string;
  decision: "allow" | "deny";
  resolved_by: string;
};
/**
 * Server→client: streamed assistant text. Emitted once a Claude session is attached (design §16).
 */
export type AssistantTextFrame = SessionEventEnvelope & {
  type?: "assistant_text";
  content: string;
};
/**
 * Server→client: Claude invoked a tool.
 */
export type ToolUseFrame = SessionEventEnvelope & {
  type?: "tool_use";
  tool_id: string;
  tool_name: string;
  tool_input?: unknown;
};
/**
 * Server→client: a tool returned.
 */
export type ToolResultFrame = SessionEventEnvelope & {
  type?: "tool_result";
  tool_id: string;
  content?: string;
  is_error?: boolean;
};
/**
 * Server→client: session state change.
 */
export type StatusFrame = SessionEventEnvelope & {
  type?: "status";
  /**
   * active | waiting_input | waiting_hook | done | error
   */
  status: string;
};
/**
 * Server→client: stream or parse error.
 */
export type ErrorFrame = SessionEventEnvelope & {
  type?: "error";
  message: string;
};
/**
 * Server→client: passive lifecycle notification (drives FCM push when no client is attached).
 */
export type NotificationFrame = SessionEventEnvelope & {
  type?: "notification";
  subkind?: string;
  title?: string;
  summary?: string;
};

/**
 * First server→client frame: stream capability negotiation. Carries no seq/ts (not a logged event).
 */
export interface HelloFrame {
  type: "hello";
  frame_version: number;
  session_id: string;
  client_id: string;
}
/**
 * A user message. Client→server it carries only content; the server echoes it back to every subscriber with the originating client_id and envelope fields.
 */
export interface UserInputFrame {
  type: "user_input";
  content: string;
  client_id?: string;
  seq?: number;
  session_id?: string;
  ts?: number;
}
/**
 * Client→server: answer a pending hook_request. First decision from any subscriber wins.
 */
export interface HookDecisionFrame {
  type: "hook_decision";
  req_id: string;
  decision: "allow" | "deny";
}
/**
 * Interrupt the running session. Client→server carries no body; echoed to subscribers with client_id + envelope.
 */
export interface InterruptFrame {
  type: "interrupt";
  client_id?: string;
  seq?: number;
  session_id?: string;
  ts?: number;
}
/**
 * Client→server: detach this connection from the session.
 */
export interface UnsubscribeFrame {
  type: "unsubscribe";
}
/**
 * Common fields on every server→client session event. Not a frame on its own.
 */
export interface SessionEventEnvelope {
  type: string;
  /**
   * monotonic per session — gap detection + cursor resume
   */
  seq: number;
  session_id: string;
  /**
   * unix seconds
   */
  ts: number;
}
